project = "Foo"

database_file_toml = "database.toml"

[sections]

[sections.asvs]
name = "OWASP ASVS"
prefix = "OWASP_ASVS"
description = "Application Security Verification Standard"
data_file = "data/OWASP.Application.Security.Verification.Standard.4.0.3-en.json"
file_type = "OWASP_ASVS_JSON"

[sections.isvs]
name = "OWASP ISVS"
prefix = "OWASP_ISVS"
description = "IoT Security Verification Standard"
data_file = "data/OWASP_ISVS-1.0RC.json"
file_type = "OWASP_ISVS_JSON"

[sections.masvs]
name = "OWASP MASVS"
prefix = "OWASP_MASVS"
description = "Mobile Application Security Verification Standard"
data_file = "data/OWASP_MASVS.yaml"
file_type = "OWASP_MASVS_YAML"

[sections.wstg]
name = "OWASP WSTG"
prefix = "OWASP_WSTG"
description = "Web Security Testing Guide"
data_file = "data/OWASP_WSTG.json"
file_type = "OWASP_WSTG_JSON"

[project_tags]
# Project offers logins
login=true
# Project offers file uploads
file_upload=true
# Project offers file downloads
file_download=true
# Project uses GraphQL
graphql=true
# Project uses http or https as web or API interface
http_or_https=true
# Uses a database (SQL, graphql, json, xml...)
database=true
# keep deleted and duplicate entries
keep_deleted=true
# IoT: project contains IoT or is at least connected to one
iot=true
# mobile application: runs on a mobile phone or similar
mobile=true
# web technology (using a web page)
web=true
# SOAP API technology being used or provided
soap=true
# REST API being used or provided ?
rest=true
# SQL being used as database ?
sql=true
# XML being used for data storage or transfer ?
xml=true