project = "Foo"

database_file_toml = "database.toml"

[sections]

[sections.asvs]
name = "OWASP ASVS"
prefix = "OWASP_ASVS"
description = "Application Security Verification Standard"
data_file = "data/OWASP.Application.Security.Verification.Standard.4.0.3-en.json"
file_type = "OWASP_ASVS_JSON"

[sections.isvs]
name = "OWASP ISVS"
prefix = "OWASP_ISVS"
description = "IoT Security Verification Standard"
data_file = "data/OWASP_ISVS-1.0RC.json"
file_type = "OWASP_ISVS_JSON"

[sections.masvs]
name = "OWASP MASVS"
prefix = "OWASP_MASVS"
description = "Mobile Application Security Verification Standard"
data_file = "data/OWASP_MASVS.yaml"
file_type = "OWASP_MASVS_YAML"

[sections.wstg]
name = "OWASP WSTG"
prefix = "OWASP_WSTG"
description = "Web Security Testing Guide"
data_file = "data/OWASP_WSTG.json"
file_type = "OWASP_WSTG_JSON"